import { createContext, useContext, useState, useEffect } from 'react';

const ThemeContext = createContext(null);

const EN = {
  dashboard: 'Dashboard',
  customers: 'Customers',
  workers: 'Workers',
  bookings: 'Bookings',
  grievances: 'Grievances',
  logout: 'Logout',
  approve: 'Approve',
  reject: 'Reject',
  block: 'Block',
  unblock: 'Unblock',
  delete: 'Delete',
  search: 'Search',
  settings: 'Settings',
  darkMode: 'Dark Mode',
  lightMode: 'Light Mode',
  language: 'Language',
  adminPortal: 'Admin Portal',
  activityFeed: 'Activity Feed',
  english: 'English',
  malayalam: 'മലയാളം',
  dashboardTitle: 'Dashboard',
  analyticsOverview: 'SmartWorkers analytics overview',
  totalCustomers: 'Total Customers',
  totalWorkers: 'Total Workers',
  totalBookings: 'Total Bookings',
  completedJobs: 'Completed Jobs',
  openGrievances: 'Open Grievances',
  totalGrievances: 'Total Grievances',
  bookingsTrend: 'Bookings Trend',
  topServices: 'Top Services',
  topCustomers: 'Top Customers',
  topWorkers: 'Top Workers',
  bookings: 'bookings',
  jobs: 'jobs',
  allStatus: 'All Status',
  pending: 'Pending',
  confirmed: 'Confirmed',
  completed: 'Completed',
  cancelled: 'Cancelled',
  worker: 'Worker',
  location: 'Location',
  date: 'Date',
  daysPrice: 'Days / Price',
  status: 'Status',
  created: 'Created',
  days: 'day(s)',
  noBookingsFound: 'No bookings found.',
  name: 'Name',
  email: 'Email',
  phone: 'Phone',
  noCustomersFound: 'No customers found.',
  noWorkersFound: 'No workers found.',
  noGrievancesFound: 'No grievances found.',
  deleteCustomer: 'Delete Customer?',
  deleteCustomerMessage: 'and all their bookings, grievances and feedback will be permanently deleted. This cannot be undone.',
  cancel: 'Cancel',
  thisCustomer: 'this customer',
  registeredCustomers: 'registered customers',
  deleteMessage: 'will be permanently deleted. This cannot be undone.',
  notUploaded: 'Not uploaded',
  searchBySubjectDescription: 'Search by subject or description…',
  all: 'All',
  open: 'Open',
  closed: 'Closed',
  active: 'Active',
  blocked: 'Blocked',
  customer: 'Customer',
  contact: 'Contact',
  actions: 'Actions',
  joined: 'Joined',
  tradeType: 'Trade Type',
  district: 'District',
  verified: 'Verified',
  unverified: 'Unverified',
  approve: 'Approve',
  reject: 'Reject',
  registeredWorkers: 'registered workers',
  subject: 'Subject',
  description: 'Description',
  resolve: 'Resolve',
  resolution: 'Resolution',
  mobile: 'Mobile',
  age: 'Age',
  mobileAge: 'Mobile / Age',
  searchByNameJobType: 'Search by name, job type, location…',
  rate: 'Rate',
  rating: 'Rating',
  rateRating: 'Rate / Rating',
  profilePhoto: 'Profile Photo',
  verificationDocuments: 'Verification Documents',
  aadhaarCard: 'Aadhaar Card',
  passbook: 'Passbook',
  documentsOpenInNewTab: 'Documents open in new tab',
};

const ML = {
  dashboard: 'ഡാഷ്‌ബോർഡ്',
  customers: 'ഉപഭോക്താക്കൾ',
  workers: 'തൊഴിലാളികൾ',
  bookings: 'ബുക്കിംഗ്',
  grievances: 'പരാതികൾ',
  logout: 'ലോഗൗട്ട്',
  approve: 'അംഗീകരിക്കുക',
  reject: 'നിരസിക്കുക',
  block: 'ബ്ലോക്ക്',
  unblock: 'അൺബ്ലോക്ക്',
  delete: 'ഇല്ലാതാക്കുക',
  search: 'തിരയുക',
  settings: 'ക്രമീകരണം',
  darkMode: 'ഡാർക്ക് മോഡ്',
  lightMode: 'ലൈറ്റ് മോഡ്',
  language: 'ഭാഷ',
  adminPortal: 'അഡ്മിൻ പോർട്ടൽ',
  activityFeed: 'പ്രവർത്തന ഫീഡ്',
  english: 'ഇംഗ്ലീഷ്',
  malayalam: 'മലയാളം',
  dashboardTitle: 'ഡാഷ്‌ബോർഡ്',
  analyticsOverview: 'SmartWorkers വിശകലനം ആപ്ലിവ്യൂ',
  totalCustomers: 'മൊത്തം ഉപഭോക്താക്കൾ',
  totalWorkers: 'മൊത്തം തൊഴിലാളികൾ',
  totalBookings: 'മൊത്തം ബുക്കിംഗുകൾ',
  completedJobs: 'പൂർത്തീകൃത ജോലികൾ',
  openGrievances: 'തുറന്ന പരാതികൾ',
  totalGrievances: 'മൊത്തം പരാതികൾ',
  bookingsTrend: 'ബുക്കിംഗ് ട്രെൻഡ്',
  topServices: 'ടോപ് സേവനങ്ങൾ',
  topCustomers: 'ടോപ് ഉപഭോക്താക്കൾ',
  topWorkers: 'ടോപ് തൊഴിലാളികൾ',
  bookings: 'ബുക്കിംഗുകൾ',
  jobs: 'ജോലികൾ',
  allStatus: 'എല്ലാ സ്ഥിതി',
  pending: 'കാത്തിരിപ്പിൽ',
  confirmed: 'സ്ഥിരീകരിച്ച',
  completed: 'പൂർത്തിയായ',
  cancelled: 'റദ്ദാക്കിയ',
  worker: 'തൊഴിലാളി',
  location: 'സ്ഥാനം',
  date: 'തീയതി',
  daysPrice: 'ദിവസങ്ങൾ / വിലയ്ക്ക്',
  status: 'സ്ഥിതി',
  created: 'സൃഷ്ടിക്കപ്പെട്ടത്',
  days: 'ദിവസം(കൾ)',
  noBookingsFound: 'കോന ബുക്കിംഗ് കണ്ടെത്തിയില്ല.',
  name: 'പേര്',
  email: 'ഇമെയിൽ',
  phone: 'ഫോൻ',
  noCustomersFound: 'കോന ഗ്രാഹകരെ കണ്ടെത്തിയില്ല.',
  noWorkersFound: 'കോന തൊഴിലാളികളെ കണ്ടെത്തിയില്ല.',
  noGrievancesFound: 'കോന പരാതികൾ കണ്ടെത്തിയില്ല.',
  deleteCustomer: 'ഗ്രാഹകനെ ഇല്ലാതാക്കണോ?',
  deleteCustomerMessage: 'കൂടാതെ അവരുടെ എല്ലാ ബുക്കിംഗ്, പരാതികൾ, ഫീഡ്‌ബാക്ക് സ്ഥിരമായി ഇല്ലാതാക്കപ്പെടും. ഇത് പിൻവലിക്കാനാവില്ല.',
  cancel: 'റദ്ദാക്കുക',
  thisCustomer: 'ഈ ഗ്രാഹകൻ',
  registeredCustomers: 'രജിസ്ട്രേഷൻ ചെയ്ത ഗ്രാഹകരുണ്ട്',
  deleteMessage: 'സ്ഥിരമായി ഇല്ലാതാക്കപ്പെടും. ഇത് പിൻവലിക്കാനാവില്ല.',
  notUploaded: 'അപ്ലോഡ് ചെയ്തില്ല',
  searchBySubjectDescription: 'വിഷയം അല്ലെങ്കിൽ വിവരണം അനുസരിച്ച് തിരയുക…',
  all: 'എല്ലാം',
  open: 'തുറന്ന',
  closed: 'അടഞ്ഞ',
  active: 'സജീവ',
  blocked: 'തടയപ്പെട്ട',
  customer: 'ഗ്രാഹകൻ',
  contact: 'ബന്ധം',
  actions: 'പ്രവർത്തനങ്ങൾ',
  joined: 'ചേരുന്നത്',
  tradeType: 'വാണിജ്യ തരം',
  district: 'ജില്ല',
  verified: 'പരിശോധിത',
  unverified: 'പരിശോധിക്കാത്ത',
  approve: 'അംഗീകരിക്കുക',
  reject: 'നിരസിക്കുക',
  registeredWorkers: 'രജിസ്ട്രേഷൻ ചെയ്ത തൊഴിലാളികൾ',
  subject: 'വിഷയം',
  description: 'വിവരണം',
  resolve: 'സമാധാനിപ്പിക്കുക',
  resolution: 'സമാധാനം',
  mobile: 'മൊബൈൽ',
  age: 'പ്രായം',
  mobileAge: 'മൊബൈൽ / പ്രായം',
  searchByNameJobType: 'പേര്, തൊഴിൽ തരം, സ്ഥാനം അനുസരിച്ച് തിരയുക…',
  rate: 'നിരക്ക്',
  rating: 'റേറ്റിംഗ്',
  rateRating: 'നിരക്ക് / റേറ്റിംഗ്',
  profilePhoto: 'പ്രൊഫൈൽ ഫോട്ടോ',
  verificationDocuments: 'പരിശോധന രേഖകൾ',
  aadhaarCard: 'ആധാർ കാർഡ്',
  passbook: 'പാസ്ബുക്ക്',
  documentsOpenInNewTab: 'രേഖകൾ പുതിയ ടാബിൽ തുറക്കുന്നു',
};

export function ThemeProvider({ children }) {
  const [isDark, setIsDark] = useState(() => {
    const stored = localStorage.getItem('sw_theme');
    return stored ? stored === 'dark' : false; // Default to light mode
  });
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('sw_lang') || 'en';
  });

  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
    localStorage.setItem('sw_theme', isDark ? 'dark' : 'light');
  }, [isDark]);

  useEffect(() => {
    localStorage.setItem('sw_lang', lang);
  }, [lang]);

  const t = (key) => (lang === 'ml' ? ML[key] : EN[key]) ?? key;

  return (
    <ThemeContext.Provider value={{ isDark, setIsDark, lang, setLang, t }}>
      {children}
    </ThemeContext.Provider>
  );
}

export const useTheme = () => useContext(ThemeContext);
